site_name: BHKLab Handbook
site_url: "https://bhklab.github.io/handbook/" # Trailing slash is recommended
repo_url: https://github.com/bhklab/handbook

markdown_extensions:
  - toc:
      permalink: '#'
      permalink_title: Anchor link to this section for reference
      toc_depth: 3
  - admonition
  - pymdownx.highlight:               # from https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html

plugins:
  - redirects:                        # handles URL redirects for moved pages
      redirect_maps:
        "index.md": "General/index.md"
  - awesome-pages                     # simplifies configuring page titles and their order
  - search                            # necessary for search functionality to work
  - git-authors                       # adds authors to pages using git history
  - autorefs:                         # automatically link to another page's ref
      resolve_closest: true
  - git-revision-date-localized:      # adds a date to the bottom of each page
      enable_creation_date: true
  - include-markdown                  # allows for including Markdown files into another Markdown file
  - mike:                             # mike handles versioned documentation
  #     # These fields are all optional; the defaults are as below...
  #     alias_type: symlink
  #     redirect_template: null
  #     deploy_prefix: ''
  #     canonical_version: null
  #     version_selector: true
  #     css_dir: css
  #     javascript_dir: js

extra:
  homepage: https://bhklab.github.io/handbook/latest
  version:
    provider: mike
    default: latest

extra_javascript:
  - assets/js/extra.js

theme:
  # logo: assets/bhklab_logo.png
  name: material
  icon:
    annotation: material/plus-circle
    admonition:
  features:
    - content.code.annotate            # adds annotations to code blocks
    - content.code.copy                # adds a copy button to code blocks
    - content.code.select              # allows selecting text in code blocks
    - content.tabs.link                # links between tabbed content
    - content.tooltips                 # enables tooltips for additional info
    - navigation.indexes               # provides index pages for navigation
    - navigation.instant               # instant loading of pages
    - navigation.instant.prefetch      # prefetches pages for instant navigation
    - navigation.path                  # displays path navigation
    - navigation.tabs                  # adds tab navigation support
    - navigation.top                   # back to top navigation button
    - navigation.tracking              # tracks page navigation statistics
    - search.highlight                 # highlights search terms
    - search.suggest                   # suggests search query completions
    - search.share                     # adds a share button to search results
    - toc.follow                       # keeps track of the current table of contents entry
  font:
    text: Red Hat Text
    code: JetBrains Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: bhklab-light
      accent: bhklab-light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: bhklab
      accent: bhklab
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - assets/css/stylesheet.css
