site_name: BHKLab Handbook
site_url: "https://bhklab.github.io/handbook/" # Trailing slash is recommended
repo_url: https://github.com/bhklab/handbook

markdown_extensions:
  - toc:
      permalink: 🔗
  - admonition
  # From https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html

plugins:
  - redirects:
      redirect_maps:
        "index.md": "General/index.md"
  # simplifies configuring page titles and their order
  - awesome-pages
  # necessary for search functionality to work
  - search
  # adds authors to pages using git history
  - git-authors
  # Automatically link to another page's ref
  - autorefs:
      resolve_closest: true
  # Adds a date to the bottom of each page
  - git-revision-date-localized:
      enable_creation_date: true
  # Allows for including Markdown files into another Markdown file
  - include-markdown
  # Mike not implemented yet
  # - mike:
  #     # These fields are all optional; the defaults are as below...
  #     alias_type: symlink
  #     redirect_template: null
  #     deploy_prefix: ''
  #     canonical_version: null
  #     version_selector: true
  #     css_dir: css
  #     javascript_dir: js

extra:
  homepage: https://bhklab.github.io/handbook/
  version:
    provider: mike
    default: latest

extra_javascript:
  - assets/js/extra.js

theme:
  # logo: assets/bhklab_logo.png
  name: material
  icon:
    annotation: material/plus-circle
    admonition:
  features:
    - content.code.annotate # Adds annotations to code blocks
    - content.code.copy # Adds a copy button to code blocks
    - content.code.select # Allows selecting text in code blocks
    - content.tabs.link # Links between tabbed content
    - content.tooltips # Enables tooltips for additional info
    - navigation.indexes # Provides index pages for navigation
    - navigation.instant # Instant loading of pages
    - navigation.instant.prefetch # Prefetches pages for instant navigation
    - navigation.path # Displays path navigation
    - navigation.tabs # Adds tab navigation support
    - navigation.top # Back to top navigation button
    - navigation.tracking # Tracks page navigation statistics
    - search.highlight # Highlights search terms
    - search.suggest # Suggests search query completions
    - toc.follow # Keeps track of the current table of contents entry
    - toc.integrate # Integrates the table of contents
  font:
    text: Red Hat Text
    code: JetBrains Mono
  palette:
    # # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme")"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: bhklab-light
      accent: bhklab-light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: bhklab
      accent: bhklab
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - assets/css/stylesheet.css
