site_name: BHKLab Handbook
site_url: "https://bhklab.github.io/handbook/" # Trailing slash is recommended
repo_url: https://github.com/bhklab/handbook

markdown_extensions:
  - toc:
      permalink: 🔗
  - admonition
  - pymdownx.details

plugins:
  # necessary for search functionality to work
  - search
  # adds authors to pages using git history
  - git-authors
  # Automatically link to another page's ref
  - autorefs:
      resolve_closest: true
  # Adds a date to the bottom of each page
  - git-revision-date-localized:
      enable_creation_date: true
  # Allows for including Markdown files into another Markdown file
  - include-markdown
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js

extra:
  version:
    provider: mike
    default: latest

theme:
  name: material
  icon:
    annotation: material/plus-circle
  font:
    text: Red Hat Text
    code: JetBrains Mono
  features:
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - search.suggest
    - search.highlight
    - navigation.indexes
    - navigation.path
    - navigation.tabs

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
