[project]
name = "bhklab-handbook"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jermiah Joseph <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[dependencies]
mkdocs = ">=1.6.0,<1.7"
mkdocs-material = ">=9.5.24,<9.6"
mkdocs-macros-plugin = ">=1.0.5,<1.1"
mkdocs-glightbox = ">=0.4.0,<0.5"
mkdocs-autorefs = ">=1.2.0,<2"
mkdocs-git-authors-plugin = ">=0.9.0,<0.10"
mike = ">=2.1.2,<2.2"
mkdocs-git-revision-date-localized-plugin = ">=1.2.9,<2"
mkdocs-include-markdown-plugin = ">=7.0.0,<8"
mkdocs-redirects = ">=1.2.1,<2"

[tasks]
build.description = "Build the documentation using MkDocs"
build.cmd = "mkdocs build -f mkdocs.yml"
build.inputs = ["docs", "mkdocs.yml"]
build.outputs = ["site"]

serve.description = "Serve the documentation to http://localhost:8001/"
serve.cmd = "mkdocs serve -f mkdocs.yml"

[environments]
lint = { features = ["lint"] }

[feature.lint.dependencies]
pre-commit = ">=3.7.1,<4"
pre-commit-hooks = ">=4.6.0,<5"
ruff = ">=0.4.8,<0.5"
taplo = ">=0.9.1,<0.10"
typos = ">=1.23.1,<2"
markdownlint-cli = ">=0.42.0,<0.43"

[feature.lint.tasks]
pre-commit-install.description = "Install pre-commit hooks"
pre-commit-install.cmd = "pre-commit install --install-hooks -t=pre-commit -t=pre-push"
pre-commit-install.inputs = [".pre-commit-config.yaml"]

lint.description = "Run pre-commit hooks"
lint.cmd = "pre-commit run --all-files --hook-stage=manual"
lint.depends-on = ["pre-commit-install"]

[pypi-dependencies]
mkdocs-awesome-pages-plugin = ">=2.9.3, <3"
mkdocs-table-reader-plugin = ">=3.1.0, <4"
