name: Conventional PR Title

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  contents: read

jobs:
  title-format:
    permissions:
      pull-requests: read  # for amannn/action-semantic-pull-request to analyze PRs
      statuses: write  # for amannn/action-semantic-pull-request to mark status of analyzed PR
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # This step will run only if the previous step fails
      - name: Comment on PR if Title Check Fails
        if: failure()  # Ensures this runs only if the previous step fails
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :warning: The title of this PR does not follow the conventional commit guidelines. Please update the title to match the required format.

            Ensure your PR title follows the pattern:
            - `fix: ...` for bug fixes
            - `feat: ...` for new features
            - `chore: ...` for general maintenance
            - etc.

            For more information, refer to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
